import cakesSpecialImg from './assets/images/cakes_special_1779797201179.png';
import browniesSpecialImg from './assets/images/brownies_special_1779797159768.png';
import cupcakesSpecialImg from './assets/images/cupcakes_special_1779797178372.png';

export interface Product {
  id: string;
  name: string;
  category: 'cakes' | 'brownies' | 'chocolate-cupcakes' | 'vanilla-cupcakes';
  price: number;
  unit: string;
  badge?: 'Bestseller' | 'New Arrival' | 'Chef Special' | 'Get 10% Off' | 'Must Try' | 'Gift Pack';
  badgeColor?: 'pink' | 'gold' | 'teal';
  description: string;
  image: string;
  features: string[];
  isVeg: boolean;
}

export const PRODUCTS: Product[] = [
  // 1. Cakes Category
  {
    id: 'cake-vanilla',
    name: 'Vanilla cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Bestseller',
    badgeColor: 'pink',
    description: 'Decadent rich vanilla bean sponge cake layered with premium white vanilla diplomat cream and white chocolate shavings.',
    image: 'https://images.unsplash.com/photo-1464349118173-a15fa55f9eb6?auto=format&fit=crop&q=80&w=600',
    features: ['Madagascar vanilla bean', 'Smooth whipping cream', 'Perfect elegant look'],
    isVeg: true,
  },
  {
    id: 'cake-blackforest',
    name: 'Black forest cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Bestseller',
    badgeColor: 'pink',
    description: 'Classic rich chocolate sponge layers filled with sweet whipped cream and juicy cherries, topped with chocolate shavings.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=600',
    features: ['Dark chocolate flakes', 'Fresh cream piping', 'Traditional cherry layers'],
    isVeg: true,
  },
  {
    id: 'cake-pineapple',
    name: 'Pineapple cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Bestseller',
    badgeColor: 'pink',
    description: 'Light and airy vanilla sponge cake layered with chopped pineapples, juicy pineapple syrup, and rich fresh cream.',
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=600',
    features: ['Real pineapple chunks', 'Soft vanilla sponge', 'Melt-in-mouth icing'],
    isVeg: true,
  },
  {
    id: 'cake-kulfi-falooda',
    name: 'Kulfi Falooda cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Chef Special',
    badgeColor: 'gold',
    description: 'Signature fusion dessert cake blending classic royal rose syrup, falooda vermicelli textures, and rich cardamom-infused kulfi flavors.',
    image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=600',
    features: ['Cardamom & Saffron notes', 'Fusion Indian flavor', 'Pistachio toppings'],
    isVeg: true,
  },
  {
    id: 'cake-gulab-gulkand',
    name: 'Gulab gulkand cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Chef Special',
    badgeColor: 'gold',
    description: 'Distinctive sponge cake layered with premium aromatic sweetened rose petal preservation (gulkand) and soft gulab jamun bites.',
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=600',
    features: ['Rich premium gulkand syrup', 'Soft gulab jamun garnish', 'Royal rose scent'],
    isVeg: true,
  },
  {
    id: 'cake-coffee',
    name: 'Coffee cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'New Arrival',
    badgeColor: 'teal',
    description: 'Aromatic espresso-infused sponge layers sandwiched between airy coffee whipped cream frosting and cocoa dust.',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=600',
    features: ['Fresh espresso infusion', 'Perfect bittersweet balance', 'Grated dark chocolate'],
    isVeg: true,
  },
  {
    id: 'cake-oreo',
    name: 'Oreo cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Must Try',
    badgeColor: 'pink',
    description: 'Crunchy crushed Oreo cookies folded into cookies-and-cream chocolate frosting inside beautiful moist cocoa cake layers.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=600',
    features: ['Real Oreo cookies', 'Creamy Oreo frosting', 'Kid-friendly bestseller'],
    isVeg: true,
  },
  {
    id: 'cake-rasmalai',
    name: 'Rasmalai cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Bestseller',
    badgeColor: 'pink',
    description: 'Decadent cake infused with royal saffron-pistachio cardamom milk, stuffed with real cottage cheese Rasmalai chunks.',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=600',
    features: ['Authentic sweet Rasmalai', 'Rich saffron-pistachio cream', 'Elegant festive highlight'],
    isVeg: true,
  },
  {
    id: 'cake-chocolate',
    name: 'Chocolate cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Must Try',
    badgeColor: 'teal',
    description: 'Perfect simple cocoa sponge layered with sweet, chocolate fresh cream and beautiful chocolate curls.',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&q=80&w=600',
    features: ['Smooth chocolate cream', 'Moist layers', 'Includes celebration accessories'],
    isVeg: true,
  },
  {
    id: 'cake-truffle',
    name: 'Chocolate truffle cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Bestseller',
    badgeColor: 'pink',
    description: 'Decadent multi-layered moist chocolate sponge sandwiched with dark chocolate ganache, finished with a mirror-glaze truffle coat.',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&q=80&w=600',
    features: ['Real premium dark chocolate', 'Moist layers', 'Includes candle & spatula'],
    isVeg: true,
  },
  {
    id: 'cake-photoprint',
    name: 'Photo print cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / 1 kg',
    badge: 'Gift Pack',
    badgeColor: 'gold',
    description: 'Fully personalized cake featuring high-definition edible sugar-sheet printing of your favorite memory photo.',
    image: 'https://images.unsplash.com/photo-1535254973040-607b474cb50d?auto=format&fit=crop&q=80&w=600',
    features: ['100% edible photo ink', 'Custom premium frame design', 'Personalized text details'],
    isVeg: true,
  },
  {
    id: 'cake-barbiedoll',
    name: 'Barbie doll cake',
    category: 'cakes',
    price: 0,
    unit: '1 kg / 1.5 kg',
    badge: 'Chef Special',
    badgeColor: 'gold',
    description: 'Stunning 3D princess doll cake styled with custom designer pink fresh cream frosting cascades and star sprinkles.',
    image: 'https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&q=80&w=600',
    features: ['Elegant Barbie centerpiece', 'Intricate rosette skirt piping', 'Perfect for child birthday theme'],
    isVeg: true,
  },
  {
    id: 'cake-plum',
    name: 'Plum cake',
    category: 'cakes',
    price: 0,
    unit: '0.5 kg / Pack of 3',
    badge: 'New Arrival',
    badgeColor: 'teal',
    description: 'Rich traditional-blend fruit cake loaded with rum-infused black currants, candied orange peels, walnuts, and fine warm spices.',
    image: 'https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=600',
    features: ['Matured dry fruits selection', 'Rich winter spice blend', 'Sponge buttery finish'],
    isVeg: true,
  },
  // 2. Brownies Category
  {
    id: 'brownie-walnut',
    name: 'Walnut Fudge Brownie',
    category: 'brownies',
    price: 0,
    unit: 'per piece / box of 4',
    badge: 'Bestseller',
    badgeColor: 'pink',
    description: 'Irresistibly dense and super chewy chocolate brownie packed with premium toasted California walnuts.',
    image: browniesSpecialImg,
    features: ['Extra fudgy fudge', 'Toasted walnuts', 'Decadent chocolate base'],
    isVeg: true,
  },
  {
    id: 'brownie-biscoff',
    name: 'Lotus Biscoff Crumble Brownie',
    category: 'brownies',
    price: 0,
    unit: 'per piece / box of 4',
    badge: 'New Arrival',
    badgeColor: 'teal',
    description: 'Fudgy brownie swirled with original creamy Lotus cookie butter spread and topped with a whole speculoos crunchy biscuit.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=600',
    features: ['Original Speculoos spread', 'Perfect crunchy-chewy duo', 'Artisanal gift look'],
    isVeg: true,
  },
  {
    id: 'brownie-overloaded',
    name: 'Overloaded Chocolate Brownie',
    category: 'brownies',
    price: 0,
    unit: 'per piece / box of 4',
    badge: 'Must Try',
    badgeColor: 'gold',
    description: 'Rich dark chocolate brownie baked with double chocolate chips and glazed with thick melted Belgian chocolate drizzle.',
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=600',
    features: ['Double chocolate chips', 'Luxury Belgian drizzle', 'Intestely rich texture'],
    isVeg: true,
  },
  // 3. Chocolate Cupcakes Category
  {
    id: 'cupcake-classic-choco',
    name: 'Classic Chocolate Fudge Cupcake',
    category: 'chocolate-cupcakes',
    price: 0,
    unit: 'per piece / Pack of 6',
    badge: 'Bestseller',
    badgeColor: 'pink',
    description: 'Fluffy cocoa muffin topped with silk chocolate fudge butter cream swirls and shiny chocolate pearls.',
    image: cupcakesSpecialImg,
    features: ['Silky buttercream', 'Rich chocolate sponge', 'Classic celebration treat'],
    isVeg: true,
  },
  {
    id: 'cupcake-oreo-choco',
    name: 'Oreo Chocolate Cupcake',
    category: 'chocolate-cupcakes',
    price: 0,
    unit: 'per piece / Pack of 6',
    badge: 'New Arrival',
    badgeColor: 'teal',
    description: 'Chocolate cupcake frosted with crunchy cookies and cream frosting and topped with mini Oreo disk.',
    image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&q=80&w=600',
    features: ['Oreo cookie crumb frosting', 'Mini Oreo topper', 'Mouthwatering kids favourite'],
    isVeg: true,
  },
  {
    id: 'cupcake-caramel-choco',
    name: 'Salted Caramel Chocolate Cupcake',
    category: 'chocolate-cupcakes',
    price: 0,
    unit: 'per piece / Pack of 6',
    badge: 'Chef Special',
    badgeColor: 'gold',
    description: 'Rich dark chocolate cake core filled with salted caramel sauce, topped with caramel buttercream swirls.',
    image: 'https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=600',
    features: ['Salted caramel core', 'Gilded golden dust', 'Decadent sweet elements'],
    isVeg: true,
  },
  // 4. Dry vanilla sponge cupcakes Category
  {
    id: 'cupcake-classic-vanilla',
    name: 'Classic Vanilla Sponge Cupcake',
    category: 'vanilla-cupcakes',
    price: 0,
    unit: 'per piece / Pack of 6',
    badge: 'Must Try',
    badgeColor: 'teal',
    description: 'Simple and perfectly baked buttery-vanilla dry sponge cupcake, extremely soft and rich in Madagascar vanilla aroma.',
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=600',
    features: ['Real vanilla bean extract', 'Pure buttery dry sponge', 'Perfect for coffee dipping'],
    isVeg: true,
  },
  {
    id: 'cupcake-tutti-frutti',
    name: 'Tutti Frutti Vanilla Cupcake',
    category: 'vanilla-cupcakes',
    price: 0,
    unit: 'per piece / Pack of 6',
    badge: 'Bestseller',
    badgeColor: 'pink',
    description: 'Traditional bakery style dry sponge cake topped and stuffed heavily with sweet, chewable colorful tutti frutti blocks.',
    image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&q=80&w=600',
    features: ['Loads of tutti frutti chunks', 'Nostalgic bakery flavor', 'Soft golden baked crust'],
    isVeg: true,
  },
  {
    id: 'cupcake-almond-vanilla',
    name: 'Almond Vanilla Sponge Cupcake',
    category: 'vanilla-cupcakes',
    price: 0,
    unit: 'per piece / Pack of 6',
    badge: 'Chef Special',
    badgeColor: 'gold',
    description: 'Healthy-alternative buttery vanilla dry cupcake studded with toasted almond shavings and a touch of nutmeg syrup.',
    image: 'https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=600',
    features: ['Flavourful almond skin shaving', 'Nourishing warm spice', 'Light breakfast style muffin'],
    isVeg: true,
  }
];

export const DELIVERY_ZONES = [
  {
    name: 'Navi Mumbai',
    areas: ['Vashi', 'Nerul', 'Koparkhairane', 'Belapur', 'Kharghar', 'Ghansoli', 'Airoli'],
    description: 'Carefully packed cake boxes delivered in air-conditioned courier transit to protect frosting.'
  },
  {
    name: 'Central Mumbai',
    areas: ['Kanjurmarg', 'Bhandup', 'Mulund', 'Ghatkopar', 'Vikhroli', 'Sion', 'Kurla', 'Dadrar'],
    description: 'Local lightning delivery from our Kanjurmarg West workspace. Freshly out of the oven.'
  },
  {
    name: 'Western Mumbai',
    areas: ['Andheri', 'Bandra', 'Borivali', 'Malad', 'Goregaon', 'Juhu', 'Santacruz'],
    description: 'Reliable doorstep delivery in specialized insulation boxes to retain ideal chilled texture.'
  }
];

export const CONTACT_INFO = {
  owner: 'Vaishali Nilesh Sarang',
  brand: 'Vaishali Bakers',
  phone: '9892047995',
  phoneDisplay: '+91 9892047995',
  email: 'vaishalisarang1985@gmail.com',
  address: '232/B-3, Dockyard Colony, Kanjurmarg (W), Mumbai 400078',
  hours: '8:00 AM — 11:00 PM',
  whatsappLink: 'https://wa.me/919892047995',
};
